# Database Configuration #
DatabaseUsername: bgUser
DatabasePassword: 123456
DatabaseHost: 10.1.4.2
DatabaseName: bgdb

# Set Socket Params Here #
SocketBindAddress: 0.0.0.0, # Bind To All Addresses By Default
Protocol: TCP # Only supports TCP for now, changing this doesn't do anything

# If Using Kafka, Include These Params, Else, Leave As Default #
KafkaHost: localhost
KafkaPort: 9092

LogPath: ../Logs/ # Set The Path For Logs
PrintLogText: True # Enable or Disable Printing Logs
SecondsToKeepLogs: 100000  # Define The Number Of Seconds To Keep Logs Before They Are Purged
ConsoleOutputEnabled: True # Enable or disable console output
ConsoleColorEnabled: True # Enable or disable console color output

# Set The Colors For Various Log Levels #
LogLevelColors:
    0: [255,255,255]
    1: [77,166,255]
    2: [179,255,217]
    3: [181,121,255]
    4: [212,0,255]
    5: [106,255,77]
    6: [204,153,0]
    7: [149,179,0]
    8: [255,255,0]
    9: [255,170,0]
    10: [255,0,0]

# Set Name For Log Strings #
LogLevelNames:
    0: System
    1: Config
    2: Audit
    3: Info
    4: Detail
    5: Fine
    6: Finer
    7: Finest
    8: Warning
    9: Severe
    10: Fatal

"Port" : 6598 # Set the port number to be used by the APIServer
# Note: There is no ip value here, as the leader is automatically used as the apiserver backend

# Apache Zookeeper Configuration #
ZKHost: 127.0.0.1
ZKPort: 2181

