# Set Logger Configuration Parameters #
EnablePrintOutput: True
EnableDatabaseOutput: False

SetMinimumLogLevel: 0

ColorizeLogOutput: True
UseTextLogLevel: False

# Set The Colors For Various Log Levels #
LogLevelColors:
    0: [255,255,255] # System
    1: [77,166,255] # Config
    2: [179,255,217] # Audit
    3: [181,121,255] # Info
    4: [212,0,255] # Detail
    5: [106,255,77] # Fine
    6: [204,153,0] # Finer
    7: [149,179,0] # Finest
    8: [255,255,0] # Warning
    9: [255,170,0] # Severe (Non Fatal)
    10: [255,0,0] # Fatal

# Set Name For Log Strings #
LogLevelNames:
    0: System
    1: Config
    2: Audit
    3: Info
    4: Detail
    5: Fine
    6: Finer
    7: Finest
    8: Warning
    9: Severe
    10: Fatal
