# Set Window Configuration Parameters #
WindowEnabled: True
WindowWidth: 1920
WindowHeight: 1080
WindowTitle: "BrainGenix-ERS"


# Renderer Settings #
RenderWidth: 800
RenderHeight: 600
EnableValidationLayers: True
MaxFramesInFlight: 2

# System Settings
ShowEditorDebugMenu: True
IsLinux: True

# Database Loading Settings #
UseDatabaseLoading: False
DatabaseHost: "127.0.0.1" # FIX ME
DatabasePort: 1 # FIX ME
DatabaseUser: "" # FIX ME
DatabaseName: "" # FIX ME
DatabasePassword: "" # FIX ME

# File Loading Params
DefaultProjectDirectory: "EditorAssets/Projects/DefaultProject/" # NOTE: PATH MUST END WITH A "/"

# Memory Settings
OverrideRAM: False
RAMSizeBytes: 42949672960
RAMMarginBytes: 4294967296

OverrideVRAM: False
VRAMSizeBytes: 10737418240
VRAMMarginBytes: 1073741824

# Set Logger Configuration Parameters #
EnablePrintOutput: True
EnableDatabaseOutput: False

SetMinimumLogLevel: 0

ColorizeLogOutput: True
UseTextLogLevel: False

# Set The Colors For Various Log Levels #
LogLevelColors:
    0: [72,92,255] # GUI Subsystem
    1: [77,166,255] # Config
    2: [179,255,217] # Audit
    3: [181,121,255] # Info
    4: [212,0,255] # Detail
    5: [106,255,77] # Fine
    6: [204,153,0] # Finer
    7: [149,179,0] # Finest
    8: [255,255,0] # Warning
    9: [255,170,0] # Severe (Non Fatal)
    10: [255,0,0] # Fatal

# Set Name For Log Strings #
LogLevelNames:
    0: GUI
    1: Config
    2: Audit
    3: Info
    4: Detail
    5: Fine
    6: Finer
    7: Finest
    8: Warning
    9: Severe
    10: Fatal


# System Information Refresh Rate
SystemDynamicInformationRefreshRate: 5.0 # Set times per second to refresh dynamic info
